name: build
on:
  push:
    branches:
      - master
      - main
      - reproduce*
    tags:
      - "*"
jobs:
  build:
    name: Build binaries
    permissions:
      contents: write
    runs-on: windows-2019
    steps:
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        name: Install msys
        with:
          update: true
          install: >-
            patch
            mingw-w64-x86_64-make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
      - name: Copy and patch
        shell: msys2 {0}
        run: ./build.sh
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generate lib files
        run: ./dll2lib.bat 64 dist\libcurl.dll
      - name: Build tarball
        shell: msys2 {0}
        run: tar cvzf curl-impersonate-chrome.tar.gz -C dist .
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: curl-impersonate-chrome.tar.gz
